# Site
name: "Unirea"
title: "Unirea"
description: "Unirea este o asociație culturală axată pe proiecte cu impact social si cultural."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
include: ["_pages"]
permalink: /:title/
url: https://asociatiaunirea.github.io/Website/
email: unireagoteborg@gmail.com

# Authors
authors:
  roxana_layrisse:
    name: Roxana Layrisse
    display_name: Roxana Layrisse
    position: Președinte
    avatar: 'assets/images/roxana_layrisse.png'
    facebook: https://www.facebook.com/roxana.layrisse
    email: unireagoteborg@gmail.com
    description: "De 38 de ani Suedia m-a îmbrățișat, dar inima mea bate neîncetat pentru valorile și tradițiile românești care mă definesc. Asociația Unirea ține românii mei, dragi, uniți. Este locul unde legăm prietenii și unde dăm dovadă că suntem o minoritate unită, aici, în Suedia."
  dragos_frincu:
    name: Dragoș Frîncu
    display_name: Dragoș Frîncu
    position: Vicepreședinte
    avatar: 'assets/images/dragos_frincu.jpeg'
    facebook: https://www.facebook.com/dragos.florinfrincu
    email: unireagoteborg@gmail.com
    description: "Locuiesc în Göteborg de 8 ani, iar aici am învățat că fiecare provocare aduce cu sine oportunități de creștere. Mă simt norocos să fac parte din această comunitate și sunt dedicat să contribui la dezvoltarea și integrarea noastră aici. Împreună, putem înfrunta orice obstacol și crea un mediu mai bun pentru toți. Iubesc România, dansul românesc și tradițiile noastre."
  andreea_pesevski:
    name: Andreea Raluca Pesevski
    display_name: Andreea Raluca Pesevski
    position: Casier
    avatar: 'assets/images/andreea_pesevski.png'
    facebook: https://www.facebook.com/andreea.pesevski
    email: unireagoteborg@gmail.com
    description: "În cei 13 ani petrecuți în Göteborg, după alți 10 în SUA, nu am încetat să caut românii, să vorbesc românește și să păstrez tradițiile noastre. Asociația Unirea este pentru mine balsamul ce-mi alină dorul de România și de oamenii ei frumoși."
  ciprian_rosu:
    name: Ciprian Roșu
    display_name: Ciprian Roșu
    position: Secretar 1
    #avatar: 'assets/images/cristina_oproiujpeg.'
    #facebook: https://www.facebook.com/tamasgabriellla
    email: unireagoteborg@gmail.com
    #description: "Călătoria mea în Suedia începe în 2018, când am rămas impresionată de harta stației centrale din Stockholm și am zis: „eu aici vreau să trăiesc”. Mă mândresc că sunt româncă și încerc, în fiecare loc unde merg, să îi învăț pe oameni că România este frumoasă, iar noi, românii, suntem oameni inimoși și frumoși."
  iulian_serghei:
    name: Iulian Serghei
    display_name: Iulian Serghei
    position: Secretar 2
    avatar: 'assets/images/iulian_serghei.jpg.'
    facebook: https://www.facebook.com/serghei.i.dumitru
    email: unireagoteborg@gmail.com
    description: "De 14 ani trăiesc în Suedia, dar legătura mea cu România și valorile sale culturale rămâne puternică. Cred într-o comunitate unită care sprijină integrarea, păstrează identitatea românească și promovează tradițiile noastre. Prin Asociația Unirea, mă implic activ pentru ca românii din Suedia să se simtă acasă și să ducă mai departe patrimoniul cultural. Împreună construim o comunitate solidă, demnă de spiritul românesc."
  cristina_oproiu:
    name: Cristina Oproiu
    display_name: Cristina Oproiu
    position: Secretar 3
    avatar: 'assets/images/cristina_oproiu.jpeg'
    facebook: https://www.facebook.com/tamasgabriellla
    email: unireagoteborg@gmail.com
    description: "Călătoria mea în Suedia începe în 2018, când am rămas impresionată de harta stației centrale din Stockholm și am zis: „eu aici vreau să trăiesc”. Mă mândresc că sunt româncă și încerc, în fiecare loc unde merg, să îi învăț pe oameni că România este frumoasă, iar noi, românii, suntem oameni inimoși și frumoși."
  mihaela_catana:
    name: Mihaela Catană
    display_name: Mihaela Catană
    position: Secretar 4
    avatar: 'assets/images/mihaela_catana.jpeg'
    facebook: https://www.facebook.com/mihaela.caita.3
    email: unireagoteborg@gmail.com
    description: "De peste 11 ani, Suedia a devenit a doua mea casă, un loc unde am evoluat pe toate planurile. Totuși, inima mea bate în continuare pentru România. Cred cu tărie în puterea comunității și în legăturile care ne unesc, indiferent de distanță. M-am alăturat asociației pentru că știu că împreună putem face lucruri minunate pentru românii din Suedia. Fiecare proiect, fiecare inițiativă ne apropie și ne dă forța de a păstra viu spiritul românesc."
  andreea_micle:
    name: Andreea Micle
    display_name: Andreea Micle
    position: Supleant 1
    avatar: 'assets/images/andreea_micle.jpg'
    facebook: https://www.facebook.com/andreea.micle.9
    email: unireagoteborg@gmail.com
    description: "Călătoria mea în Suedia a început în 2011. Deși viața m-a purtat departe de casă, România rămâne mereu în sufletul meu. Oriunde mă aflu, port cu mândrie tradițiile, cultura și valorile care m-au format. Cred în puterea comunității și în frumusețea de a ne susține unii pe alții, indiferent de distanță."
  irina_sherwany:
    name: Irina Sherwany 
    display_name: Irina Sherwany
    position: Supleant 2
    avatar: 'assets/images/irina_sherwany.jpg'
    facebook: https://www.facebook.com/irina.sherwany
    email: unireagoteborg@gmail.com
    description: "Cu toate ca sunt plecată de aproape 38 de ani din România la o vârstă fragedă nu am uitat niciodată de rădăcinile mele. Iubesc România și tot ce are de a face cu această țară minunată. România noastră pe care încercăm să o promovăm să o iubim și să o susținem chiar dacă ne aflăm pe alte meleaguri."
  delia_gherman:
    name: Delia Gherman 
    display_name: Delia Gherman
    position: Supleant 3
    avatar: 'assets/images/delia_gherman.jpeg'
    facebook: https://www.facebook.com/delia.gherman.7
    email: unireagoteborg@gmail.com
    description: "Venită la varsta de 19 ani în Suedia mi-a fost greu să mă adaptez, dar datorita familiei și românilor care i-am cunoscut pe parcursul vieții dar și prin intermediul asociației, viața îmi este mult mai frumoasă . Sunt o persoană sociala, prietenoasă, îmi place să întâlnesc oameni, să ascult muzică și să mă bucur de viață."
  ion_drumea:
    name: Ion Drumea
    display_name: Ion Drumea
    position: Supleant 4
    avatar: 'assets/images/ion_drumea.png'
    facebook: https://www.facebook.com/drumeaionnicolae
    email: unireagoteborg@gmail.com
    description: "Am ajuns în Suedia în 2014, în orașul Göteborg. Sunt o persoană sociabilă, corectă și luptătoare pentru dreptate. Sunt aici datorită încrederii colegilor mei minunați din Asociația „Unirea”. Mă bucur că proiectele și activitățile tradiționale și culturale apropie tot mai mulți români unii de alții. Sunt mândru că sunt român!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Load paths
load_paths:
    - _sass

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
